language: cpp
sudo: required
dist: trusty
before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
script:
    - df -h
    - free -m
    - cat /proc/cpuinfo
