language: c
compiler: gcc
sudo: required
dist: trusty
cache:
  apt: true
  directories:
  - cached
script:
  - make check
  - mkdir -p cached
  - touch cached/cached.txt
  - cat cached/cached.txt
  - echo "test" > cached/cached.txt
