language: cpp
sudo: required
dist: trusty
install:
    - sudo apt-get update
    - sudo apt-get install --no-install-recommends python3-zmq
script:
  - ls /usr/lib/python3/dist-packages/zmq/
  - echo $PYTHONPATH
