sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
  - dummy/foo
  - dummy/bar
  - $HOME/.ccache

script:
  - echo "ccache before:"
  - find ~/.ccache/
  - echo ";" >> dummy/foo/file
  - echo ";" >> test.c
  - ccache gcc -c test.c -o test.o
  - echo "ccache after:"
  - find ~/.ccache/
