sudo: required
dist: trusty
os: linux
language: minimal
cache:
  ccache: true
  directories:
  - dummy/foo
  - dummy/bar

script:
    echo ";" >> dummy/foo/file
    echo ";" >> dummy/bar/file
    echo ";" >> test.c
    ccache gcc -c test.c -o test.o
