language: c
compiler: gcc
sudo: false
addons:
  apt:
    packages:
      - gcc-mingw-w64-x86-64
      - binutils-mingw-w64-x86-64
      - wine
cache:
  apt: true
  directories:
  - cached
script:
  - make check
  - mkdir -p cached
  - echo "test" > cached/cached.txt
