language: cpp
sudo: required
dist: trusty
before_install:
    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
install:
env:
  global:
    - TMPDIR=/tmp/tmpfs/tmp
    - CCACHE_DIR=${TMPDIR}/.ccache
script:
    - mkdir -p ${TMPDIR}
    - mkdir -p ${CCACHE_DIR}
    - sudo mount -t tmpfs -o size=1000M,mode=0777 tmpfs ${TMPDIR}
    - touch ${TMPDIR}/test
    - df -h
    - free -m
    - make check
