os: linux
language: cpp
sudo: false
env:
  global:
    - CCACHE_SIZE=100M
    - CCACHE_TEMPDIR=/tmp/.ccache-temp
    - CCACHE_COMPRESS=1
cache:
  directories:
  - $HOME/.ccache
script:
    - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ccache --max-size=$CCACHE_SIZE; fi
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export CCACHE_READONLY=1; fi
    - echo $CCACHE_READONLY
    - make
